---
driver:
  name: vagrant
#  provider: parallels

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: 18
  chef_license: accept
  client_rb:
    ohai.optional_plugins: [":Passwd"]

platforms:
  - name: ubuntu-20.04
    run_list:
      - recipe[net_setup::default]
  - name: centos-7.2
    run_list:
      - recipe[net_setup::default]
  - name: rockylinux-9.4
    run_list:
      - recipe[fake::default]
    driver:
      network:
      - ["private_network", {ip: "10.19.75.10"}]
      - ["private_network", {ip: "10.19.75.11"}]
      - ["private_network", {ip: "10.19.75.12"}]
      - ["private_network", {ip: "10.19.75.13"}]
  - name: win-2012r2
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      network:
        - ["forwarded_port", {guest: 3389, host: 3389}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0029", auto_config: false}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0031", auto_config: false}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0033"}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0035", auto_config: false}]

suites:
  - name: default
    run_list:
      - recipe[fake::default]
